name: Security Scan

on:
  push:
    branches:
      - main
      - feat/helm
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'
permissions:
  contents: read
  security-events: write
jobs:

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend User Image
        run: docker build -t backend-user:${{ github.sha }} ./backend_User

      - name: Build Backend Product Image
        run: docker build -t backend-product:${{ github.sha }} ./backend_Product

      - name: Build Backend Order Image
        run: docker build -t backend-order:${{ github.sha }} ./backend_Order

      - name: Build Frontend Image
        run: docker build -t frontend:${{ github.sha }} ./frontend

      - name: Build Gateway Image
        run: docker build -t gateway:${{ github.sha }} ./gateway

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'backend-user:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'


  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          path: '.'
          format: 'SARIF'
          project: 'E-commerceApplication'
          out: 'reports'
          args: >
            --enableExperimental

      - name: Upload Dependency Check Results
        uses: github/codeql-action/upload-sarif@v3 
        with:
          sarif_file: 'reports/dependency-check-report.sarif'
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}