apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
  namespace: jenkins-agents
spec:
  containers:
  # 1. Container cho Node.js: Dùng để cài lib, chạy test
  - name: nodejs
    image: node:20-alpine
    command:
    - cat
    tty: true

  # 2. Container cho Trivy: Dùng để scan lỗ hổng bảo mật
  - name: trivy
    image: aquasec/trivy:0.49.1
    command:
    - cat
    tty: true

  # 3. Container cho Kaniko: Build image mà không cần Docker-in-Docker
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - 9999999
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-credentials
      items:
      - key: .dockerconfigjson
        path: config.json